# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'Der Stundenplan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Der Stundenplan

pod 'SwiftKeychainWrapper'
pod 'SwiftDate', '~> 5.0'
pod 'EasyAnimation'
pod 'JZCalendarWeekView', '~> 0.7.0'
end
